import { Inter } from 'next/font/google'
import './page.module.css'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Contact List',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
     <html lang="en">
       <body>
         <nav>
           <nav>
             <a href='/'>Home</a>
             <br/>
             <Link href='/roster/new'>Add Contact</Link>
             <br/>
             <Link href='/roster'>Contacts</Link>
             <br/>
      
           </nav>
         </nav>
         {children}
       </body>
     </html>
   )
 }
 